from selenium import webdriver
from selenium.webdriver.common.by import By
import time
driver =  webdriver.Chrome()
driver.maximize_window()
time.sleep(2)
driver.get("https://pos-app.macomal.com/")
driver.find_element(By.XPATH,'//*[@name="phoneNo"]').send_keys('9854126358')
driver.find_element(By.NAME,"password").send_keys("nirmesh")
time.sleep(2)
driver.find_element(By.XPATH,"//button[@type='submit']").click()
time.sleep(4)
driver.find_element(By.XPATH,"//button[@class='btn btn-outline-primary']").click()
time.sleep(2)
driver.get("https://pos-app.macomal.com/company-master")
driver.find_element(By.XPATH,"//button[@role='button']").click()
time.sleep(1)
driver.find_element(By.ID,"companyName").send_keys('webtek enterprises')
driver.find_element(By.ID,"phoneNo").send_keys('9711356070')
driver.find_element(By.ID,"email").send_keys('webit@gmail.com')
driver.find_element(By.ID,"panNo").send_keys('BSVPC8743C')
driver.find_element(By.ID,"gstNo").send_keys('29AAACC1206D2ZB')
time.sleep(1)
driver.find_element(By.ID,"city").send_keys('punjab')
driver.find_element(By.ID,"address").send_keys("address")
driver.find_element(By.XPATH,"//button[normalize-space()='Submit']").click()
time.sleep(2)
## User Reset ##
#driver.find_element(By.XPATH,"//tbody/tr[10]/td[1]/div[1]/div[1]//*[name()='svg']").click()
#time.sleep(2)
