import time
from selenium import webdriver
from selenium.webdriver.common.by import By
driver = webdriver.Chrome()
# driver.implicitly_wait(10)
driver.get("https://pos-app.macomal.com")
driver.maximize_window()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@name="phoneNo"]').send_keys(9854126358)
driver.find_element(By.NAME,"password").send_keys("nirmesh")
time.sleep(1)
driver.find_element(By.XPATH,"//button[normalize-space()='Sign In']").click()
time.sleep(1)
driver.find_element(By.XPATH,'//button[text()="PROCEED"]').click()
time.sleep(2)
driver.find_element(By.XPATH,"//li[@title='Master']//div[@class='menu-close-side-bar']").click()
time.sleep(1)
driver.find_element(By.XPATH,"//span[normalize-space()='Brand Master']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//span[normalize-space()='Category Master']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//span[normalize-space()='Colour Master']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//span[normalize-space()='Size Master']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//span[normalize-space()='Supplier Master']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//span[normalize-space()='Product Master']").click()
time.sleep(1)
driver.find_element(By.XPATH,"//span[normalize-space()='User Details']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//span[normalize-space()='Company Master']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//span[normalize-space()='Invoice Series']").click()
time.sleep(4)

print('hello world')