import time
from selenium import webdriver
from selenium.webdriver import ActionChains, Keys
from selenium.webdriver.common.by import By
driver = webdriver.Chrome()
driver.get("https://pos-app.macomal.com/")
driver.maximize_window()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@name="phoneNo"]').send_keys('9854126358')
driver.find_element(By.NAME,"password").send_keys("nirmesh")
time.sleep(2)
driver.find_element(By.XPATH,"//button[@type='submit']").click()
time.sleep(3)
driver.find_element(By.XPATH,"//button[@class='btn btn-outline-primary']").click()
time.sleep(4)
driver.get("https://pos-app.macomal.com/product-master")
driver.find_element(By.XPATH,"//input[@id='productName']").send_keys('data cable')
time.sleep(2)
driver.find_element(By.ID,"productSymbol").send_keys('type C')
driver.find_element(By.XPATH,"//input[@id='productSKU']").send_keys('884376473')
time.sleep(3)
driver.find_element(By.XPATH,"//input[@id='brandName']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//li[@id='brandName-option-3']").click()
time.sleep(2)
driver.find_element(By.XPATH,'//div[input[@name="categoryName"]]/div/button').send_keys('sound bar')
time.sleep(1)
driver.find_element(By.XPATH,"//input[@id='colourName']").click()
time.sleep(1)
driver.find_element(By.XPATH,"//li[@id='colourName-option-4']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='sizeName']").click()
time.sleep(1)
driver.find_element(By.XPATH,"//li[@id='sizeName-option-2']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='gstPercentage']").send_keys("12")
time.sleep(2)
driver.find_element(By.XPATH,"//button[normalize-space()='Add']").click()
time.sleep(1)
## User reset ##
driver.find_element(By.XPATH,'//*[@id="root"]/div/div[2]/div[2]/div[3]/div/div/table/tbody/tr[1]/td[1]/div/div[1]').click()
time.sleep(2)
driver.find_element(By.XPATH,"//button[normalize-space()='Reset']").click()
time.sleep(2)
## User Update ##
driver.find_element(By.XPATH,'//*[@id="root"]/div/div[2]/div[2]/div[3]/div/div/table/tbody/tr[1]/td[1]/div/div[1]').click()
time.sleep(1)
driver.find_element(By.XPATH,"//button[normalize-space()='Update']").click()
time.sleep(2)
## User deleted ##
driver.find_element(By.XPATH,"//tbody/tr[1]/td[1]/div[1]/div[2]//*[name()='svg']//*[name()='path' and contains(@d,'M6 19c0 1.')]").click()
time.sleep(4)
driver.find_element(By.XPATH,"//button[normalize-space()='Yes, delete it!']").click()
time.sleep(4)