import time
from selenium import webdriver
from selenium.webdriver import ActionChains, Keys
from selenium.webdriver.common.by import By
driver = webdriver.Chrome()
driver.get("https://pos-app.macomal.com/")
driver.maximize_window()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@name="phoneNo"]').send_keys('9854126358')
driver.find_element(By.NAME,"password").send_keys("nirmesh")
time.sleep(2)
driver.find_element(By.XPATH,"//button[@type='submit']").click()
time.sleep(3)
driver.find_element(By.XPATH,"//button[@class='btn btn-outline-primary']").click()
time.sleep(4)
driver.get("https://pos-app.macomal.com/user-details")
driver.find_element(By.ID,"userName").send_keys("macco")
time.sleep(1)
driver.find_element(By.XPATH,"//input[@id='«r1»']").send_keys('123456')
time.sleep(1)
driver.find_element(By.XPATH,"//input[@id='«r3»']").send_keys('123456')
time.sleep(2)
driver.find_element(By.ID,"phoneNo").send_keys('9911240301')
driver.find_element(By.ID,"email").send_keys('maccoinfo@gmail.com')
time.sleep(1)
driver.find_element(By.XPATH,"//div[6]//div[1]//div[1]").click()
time.sleep(1)
driver.find_element(By.XPATH,"//li[normalize-space()='maco private limited']").click()
driver.find_element(By.XPATH,"//div[7]//div[1]//div[1]").click()
time.sleep(1)
driver.find_element(By.XPATH,"//li[normalize-space()='Member']").click()
driver.find_element(By.XPATH,"//button[normalize-space()='Add']").click()
time.sleep(2)
## User reset ##
driver.find_element(By.XPATH,'//*[@id="root"]/div/div[2]/div[2]/div[3]/div/div/table/tbody/tr[1]/td[1]/div/div[1]').click()
time.sleep(1)
driver.find_element(By.XPATH,"//button[normalize-space()='Reset']").click()
time.sleep(1)
##  User update ##
driver.find_element(By.XPATH,'//*[@id="root"]/div/div[2]/div[2]/div[3]/div/div/table/tbody/tr[1]/td[1]/div/div[1]').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="root"]/div/div[2]/div[2]/div[1]/div/div/div[8]/div/button[2]').click()
time.sleep(1)
## User deleted ##
driver.find_element(By.XPATH,"//tbody/tr[1]/td[1]/div[1]/div[2]//*[name()='svg']//*[name()='path' and contains(@d,'M6 19c0 1.')]").click()
time.sleep(3)
driver.find_element(By.XPATH,"//button[normalize-space()='Yes, delete it!']").click()
time.sleep(2)
